### ISSUE TITLE
is there a way that I can make some components based on `ZView` like `Toast`?

### ISSUE THREAD

**Issue by chj-damon** [intergalacticspacehighway/react-native-z-view#1]
I want to make a `Toast` component that based on `ZView` since `Toast` should be above all the views.

I know I can directly use `ZView` to wrap my component, but this time I want to make a static function so I can dynamically create it, like this:
```
<Button onPress={() => Toast.show(xxx)} >show Toast</Button>
```

and use `Toast.hide()` to remove it.

any suggestions?

**Comment by intergalacticspacehighway** [comment]
yeah here is a simple overview.

```jsx
export let Toast = { show: (message) => {}, hide: () => {} };

const ToastComp = () => {
    const [message, setMessage] = useState(null);
    
    useEffect(() => {
        Toast.show = (message) => setMessage(message);
        Toast.hide = () => setMessage(null)
    }, []);
    
    return message ? <ZView bottom={10}><Text>{message}</Text></ZView> : null
}
```

Mount the `ToastComp` in your root view and you can use Toast API anywhere once it is **mounted**.

**Comment by chj-damon** [comment]
I have another idea if you can export the native `addView` and `removeView` method, so maybe it would be better to do so?
